config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :folks
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folk.rb
class Folk < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/folks_controller.rb
class FolksController < ApplicationController
  before_action :set_folk, only: %i[ show edit update destroy ]

  # GET /folks or /folks.json
  def index
    @folks = Folk.all
  end

  # GET /folks/1 or /folks/1.json
  def show
  end

  # GET /folks/new
  def new
    @folk = Folk.new
  end

  # GET /folks/1/edit
  def edit
  end

  # POST /folks or /folks.json
  def create
    @folk = Folk.new(folk_params)

    respond_to do |format|
      if @folk.save
        format.html { redirect_to @folk, notice: "Folk was successfully created." }
        format.json { render :show, status: :created, location: @folk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @folk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folks/1 or /folks/1.json
  def update
    respond_to do |format|
      if @folk.update(folk_params)
        format.html { redirect_to @folk, notice: "Folk was successfully updated." }
        format.json { render :show, status: :ok, location: @folk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @folk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folks/1 or /folks/1.json
  def destroy
    @folk.destroy
    respond_to do |format|
      format.html { redirect_to folks_url, notice: "Folk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folk
      @folk = Folk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folk_params
      params.require(:folk).permit(:first_name, :last_name, :email, :mobile_number, :twitter, :date_of_joining, :nick_name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @name = 'Ramaprasath Appaiya'
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/folks_helper.rb
module FolksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/folks/_form.html.erb
<%= form_with(model: folk, local: true) do |form| %>
  <% if folk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folk.errors.count, "error") %> prohibited this folk from being saved:</h2>

      <ul>
      <% folk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
  </div>
  <div class="pad5"></div>
  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
  </div>
  <div class="pad5"></div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control', placeholder: 'Email ID' %>
  </div>
  <div class="pad5"></div>
  <div class="field">
    <%= form.label :mobile_number %>
    <%= form.text_field :mobile_number, class: 'form-control', placeholder: 'Mobile Number' %>
  </div>
  <div class="pad5"></div>
  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class: 'form-control', placeholder: 'Twitter Handle' %>
  </div>
  <div class="pad5"></div>
  <div class="field">
    <%= form.label :date_of_joining %>
    <%= form.text_field :date_of_joining, class: 'form-control', placeholder: 'Date of Joining to IO' %>
  </div>
  <div class="pad5"></div>
  <div class="field">
    <%= form.label :nick_name %>
    <%= form.text_field :nick_name, class: 'form-control', placeholder: 'How can we call any nickname ?' %>
  </div>
  <div class="pad5"></div>
  <div class="actions">
    <%= form.submit class: "btn btn-sm btn-secondary" %>
  </div>
<% end %>

app/views/folks/edit.html.erb
<div class="section560">
  <h1>Update Folk</h1>
  <%= render 'form', folk: @folk %>
  <div class="pad10"></div>
  <%= link_to 'Show', @folk, class: "btn btn-sm btn-info" %> &nbsp;
  <%= link_to 'Back', folks_path, class: "btn btn-dark btn-sm" %>
</div>

app/views/folks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Folks - <%= Rails.env.stag? %>  </h1>

<table class="table table-light table-striped table-bordered">
  <thead>
    <tr class="table-dark">
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Mobile number</th>
      <th>Twitter</th>
      <th>Date of joining</th>
      <th>Nick name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folks.each do |folk| %>
      <tr>
        <td><%= folk.first_name %></td>
        <td><%= folk.last_name %></td>
        <td><%= folk.email %></td>
        <td><%= folk.mobile_number %></td>
        <td><%= folk.twitter %></td>
        <td><%= folk.date_of_joining %></td>
        <td><%= folk.nick_name %></td>
        <td><%= link_to 'Show', folk %></td>
        <td><%= link_to 'Edit', edit_folk_path(folk) %></td>
        <td><%= link_to 'Destroy', folk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a Folk ?', new_folk_path, class: "btn btn-secondary btn-sm" %>

app/views/folks/new.html.erb
<div class="section560">
  <h1>Add a New Folk</h1>
  <%= render 'form', folk: @folk %>
  <div class="pad10"></div>
  <%= link_to 'Back', folks_path, class: "btn btn-dark btn-sm" %>
</div>

app/views/folks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card text-center">
  <div class="card-header">
    <b>
      Details of <%= @folk.first_name + ' ' + @folk.last_name %>
    </b>
  </div>
  <div class="card-body">
    <p>
      <strong>First name:</strong>
      <%= @folk.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @folk.last_name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @folk.email %>
    </p>

    <p>
      <strong>Mobile number:</strong>
      <%= @folk.mobile_number %>
    </p>

    <p>
      <strong>Twitter:</strong>
      <%= @folk.twitter %>
    </p>

    <p>
      <strong>Date of joining:</strong>
      <%= @folk.date_of_joining %>
    </p>

    <p>
      <strong>Nick name:</strong>
      <%= @folk.nick_name %>
    </p>

    <%= link_to 'Edit', edit_folk_path(@folk), class: "btn btn-sm btn-info" %> &nbsp;
    <%= link_to 'Back', folks_path, class: "btn btn-dark btn-sm" %>
  </div>
</div>

app/views/home/_footer.html.erb
<div id="copyright" class="mrgntop20 mrgnbtm20">
  <div class="pad10 bdr txtCenter">&copy; Folks 2020 - <%= Time.current.year %></div>
</div>

app/views/home/_header.html.erb
<%# <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid"> %>
    <%# link_to 'Folks', root_path, class: "navbar-brand"  %>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
    <%# <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"> %>
          <%# link_to "About Us", home_about_path, class: "nav-link" %>
        <%# </li>
      </ul>
    </div>
  </div>
</nav> %>


<header id="headerBar" class="flex flexAlignItemsCenter flexJustifyBetween boxShadowDown horizontalScrollContainer scrollBarStyle">
  <nav id="navBar" class="flex flexJustifyBetween padleft30">
    <a>
      <%= link_to "Me", root_path, class: "item" %>
    </a>
    <a>
      <%= link_to "Folks List", folks_path, class: "item" %>
    </a>
    <a>
      <%= link_to "About Us", home_about_path, class: "item" %>
    </a>

    <% if user_signed_in? %>
      <a>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete ,class: "item" %>
      </a>
      <a>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "item" %>
      </a>
    <% else %>
      <a>
        <%= link_to "Sign Up", new_user_registration_path, class: "item" %>
      </a>
      <a>
        <%= link_to "Sign In", new_user_session_path, class: "item" %>
      </a>
    <% end %>
  </nav>
</header>

app/views/home/about.html.erb
<h1 class="bdr"> $$$$$$ This is About US $$$$$ </h1>

app/views/home/index.html.erb
<h1>Hello <%= @name %> !!!!</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Folks</title>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>
  <body>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'home/header' %>
      <div class="section1366 mrgntop70">
        <%= yield %>
      </div>
      <%= render 'home/footer' %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>